version: '3.6'

services:
  alpine-terraform-websocketd-hl:
    build: .
    image: hackinglab/alpine-terraform-websocketd-hl:3.2
    environment:
      - S6_KILL_FINISH_MAXTIME=3600000
    stop_grace_period: 1h
    ports:
      - 80:80
